### ISSUE TITLE
Bug in can::tryToSend()

### ISSUE THREAD

**Issue by DirkMeintjies** [pierremolinaro/acan-esp32#2]
In your function can::tryToSend() you check the mDriverIsSending variable, and if it is true (implying that a previous TX is still in progress) you add the new message to the queue. However, it is possible to get a TX interrupt after this check, but before putting the message in the queue. Then the message ends up in the queue and is never transmitted. The solution is prevent TX interrupt from occuring (disable ints) before checking mDriverIsSending, and re-enable after placing message in queue.

**Comment by pierremolinaro** [comment]
Yes, you are right, this is a mistake. I'm correcting it and updating the library.

Best Regards,

Pierre
