### ISSUE TITLE
esp32-S3

### ISSUE THREAD

**Issue by taoloo897** [pierremolinaro/acan-esp32#8]
Hi again and thanks a lot for your work.
With esp32 wroomer 32U/D works greate. Today i bought a esp32-s3 with tft screen and it not work.
This is the board
https://vi.aliexpress.com/item/1005005187357655.html?spm=a2g0o.order_list.order_list_main.5.3e181802D58sAr&gatewayAdapt=glo2vnm
Sketch is uploaded ok but after recieved on serial the first debug line "  Serial.println("Configure ESP32 CAN");"
nothing happen.
This bord had available pins 15,16,17,18,43,44. I tried them all. The same thing.
Please if you have any ideea.
Thanks in advance

PS , this is what i received and esp reboot itself

21:41:04.959 -> 
21:41:04.959 -> ELF file SHA256: 8e45cccc34f74f6c
21:41:04.959 -> 
21:41:04.959 -> Rebooting...
21:41:04.959 -> ESP-ROM:esp32s3-20210327
21:41:04.959 -> Build:Mar 27 2021
21:41:04.959 -> rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
21:41:04.959 -> Saved PC:0x40376c78
21:41:04.959 -> SPIWP:0xee
21:41:04.959 -> mode:DIO, clock div:1
21:41:04.959 -> load:0x3fce3808,len:0x44c
21:41:04.959 -> load:0x403c9700,len:0xbe4
21:41:04.959 -> load:0x403cc700,len:0x2a68
21:41:04.959 -> entry 0x403c98d4
21:41:05.154 -> Configure ESP32 CAN
21:41:10.393 -> Saved PC:0x40376c78
21:41:10.393 -> SPIWP:0xee
21:41:10.393 -> mode:DIO, clock div:1
21:41:10.393 -> load:0x3fce3808,len:0x44c
21:41:10.393 -> load:0x403c9700,len:0xbe4
21:41:10.393 -> load:0x403cc700,len:0x2a68
21:41:10.425 -> entry 0x403c98d4
21:41:10.588 -> Configure ESP32 CAN
21:41:15.606 -> E (10297) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
21:41:15.606 -> E (10297) task_wdt:  - IDLE (CPU 0)
21:41:15.606 -> E (10297) task_wdt: Tasks currently run

**Comment by pierremolinaro** [comment]
Hi,

I've just looked at the ESP32S3 documentation, and I have discovered that the modules are not at the same address as for the ESP32.

I've made a new release with correct addresses at:
	https://github.com/pierremolinaro/acan-esp32

Can you try this ?

Unfortunatly, I have no ESP32-S3 board, so I cannot check my self.

Pierre

**Comment by pierremolinaro** [comment]
Hello,

Currently, I have no ESP-S3 board, so I cannot help you.

I have ordered some XIAO ESP32-S3 boards, I will receive them in the next few days.

I'll let you know as soon as I've made any progress.

Pierre

**Comment by taoloo897** [comment]
Hi again and thanks.
I saw a little, because i don;t know very good the c or c++ , language in you made the library, do you use TWAI libray too?

**Comment by pierremolinaro** [comment]
Hi,

I have began my library before the TWAI api was exposed, so I do not use it.

I have just received the XIAO ESP32-S3 boards, I begin the tests this afternoon.

Pierre

**Comment by pierremolinaro** [comment]
I think it is now ok for an ESP32S3. Can you check with the library at:
	https://github.com/pierremolinaro/acan-esp32

Pierre

**Comment by taoloo897** [comment]
I downloaded your library again and put over the old one.
Nothing receive on canbus and nothing display on serial with s3, with wroomer works .
STRANGE!

**Comment by pierremolinaro** [comment]
Sorry, I did not check bit rate, there is a bug here.

**Comment by pierremolinaro** [comment]
Ok, I have understood : the TWAI_BUS_TIMING_0 is not the same, different in ESP32 and ESP32-S3. I make a release soon.

**Comment by pierremolinaro** [comment]
I have fixed the bit rate bug for ESP32S3. Can you check with the library at:
	https://github.com/pierremolinaro/acan-esp32

Pierre

**Comment by taoloo897** [comment]
IT WORKS GREATE on Lilygo t-hmi 2.8" esp32 S3. Many Thanks.

**Comment by pierremolinaro** [comment]
Thank you !

In summary, there were two points to correct:
	- the TWAI module address is at 0x3ff6B000 for the ESP32, and 0x6002B000 for the ESP32S3 and the ESP23C3;
	- the TWAI_BUS_TIMING_0_REG register field mapping did change:
		* ESP32 : TWAI_BAUD_PRESC bit field at 0:5, TWAI_SYNC_JUMP_WIDTH at 6:7;
		* ESP32S3 and ESP32C3 : TWAI_BAUD_PRESC bit field at 0:13, TWAI_SYNC_JUMP_WIDTH at 14:15.

Pierre
